# SimpleImputer (sklearn) for handling the null values

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_1=pd.Series([1,2,3,4,5,6])
df_2=pd.Series([x for x in range(7,13)])
df_3=pd.Series([x*0 for x in range(6)])

In [3]:
d1=pd.DataFrame({'D1':df_1})
d2=pd.DataFrame({'D2':df_2})
d3=pd.DataFrame({'D3':df_3})

In [4]:
df_=pd.concat([d1,d2],axis=1)

In [5]:
final_df=pd.concat([df_,d3],axis=1)

In [6]:
final_df

D1  D2  D3
0   1   7   0
1   2   8   0
2   3   9   0
3   4  10   0
4   5  11   0
5   6  12   0

In [7]:
final_df['D2'].loc[4:6]=np.nan

In [8]:
final_df

D1    D2  D3
0   1   7.0   0
1   2   8.0   0
2   3   9.0   0
3   4  10.0   0
4   5   NaN   0
5   6   NaN   0

In [9]:
final_df['D1'].loc[0:3]=999

/var/folders/d6/s0gglf8932vfsdjpfxwvry340000gp/T/ipykernel_1581/417353416.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['D1'].loc[0:3]=999


In [10]:
final_df

D1    D2  D3
0  999   7.0   0
1  999   8.0   0
2  999   9.0   0
3  999  10.0   0
4    5   NaN   0
5    6   NaN   0

In [11]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [12]:
final_df=imputer.fit_transform(final_df)

In [13]:
final_df

array([[999. ,   7. ,   0. ],
       [999. ,   8. ,   0. ],
       [999. ,   9. ,   0. ],
       [999. ,  10. ,   0. ],
       [  5. ,   8.5,   0. ],
       [  6. ,   8.5,   0. ]])

In [14]:
imp=SimpleImputer(missing_values=999,strategy='most_frequent')

In [15]:
final_df=imp.fit_transform(final_df)

In [16]:
final_df

array([[ 5. ,  7. ,  0. ],
       [ 5. ,  8. ,  0. ],
       [ 5. ,  9. ,  0. ],
       [ 5. , 10. ,  0. ],
       [ 5. ,  8.5,  0. ],
       [ 6. ,  8.5,  0. ]])

In [17]:
imp_1=SimpleImputer(missing_values=0,strategy='mean')

In [19]:
final_df=imp_1.fit_transform(final_df)

In [20]:
final_df

array([[ 5. ,  7. ],
       [ 5. ,  8. ],
       [ 5. ,  9. ],
       [ 5. , 10. ],
       [ 5. ,  8.5],
       [ 6. ,  8.5]])